package Pratica06;

public class Main {


    public static void main(String[] args) throws Exception {
        
        JAGM Grafo1,Grafo2;
        JGrafo grafo = new JGrafo (9, 16);
        JGrafo.Aresta a1 =  new JGrafo.Aresta (0, 1, 5);
        grafo.insereAresta (0,1,a1.peso());
        grafo.insereAresta (1,0,a1.peso());
        JGrafo.Aresta a2 =  new JGrafo.Aresta (0, 3, 10);
        grafo.insereAresta (0,3,a2.peso());
        grafo.insereAresta (3,0,a2.peso());
        JGrafo.Aresta a3 =  new JGrafo.Aresta (0, 4, 5);
        grafo.insereAresta (0,4,a3.peso());
        grafo.insereAresta (4,0,a3.peso());
        JGrafo.Aresta a4 =  new JGrafo.Aresta (0, 6, 10);
        grafo.insereAresta (0,6,a4.peso());
        grafo.insereAresta (6,0,a4.peso());
        JGrafo.Aresta a5 =  new JGrafo.Aresta (0, 7, 10);
        grafo.insereAresta (0,7,a5.peso());
        grafo.insereAresta (7,0,a5.peso());
        JGrafo.Aresta b1 =  new JGrafo.Aresta (1, 5, 5);
        grafo.insereAresta (1,5,b1.peso());
        grafo.insereAresta (5,1,b1.peso());
        JGrafo.Aresta b2 =  new JGrafo.Aresta (1, 7, 5);
        grafo.insereAresta (1,7,b2.peso());
        grafo.insereAresta (7,1,b2.peso());
        JGrafo.Aresta b3 =  new JGrafo.Aresta (1, 8, 10);
        grafo.insereAresta (1,8,b3.peso());
        grafo.insereAresta (8,1,b3.peso());
        JGrafo.Aresta c1 =  new JGrafo.Aresta (2, 3, 5);
        grafo.insereAresta (2,3,c1.peso());
        grafo.insereAresta (3,2,c1.peso());
        JGrafo.Aresta c2 =  new JGrafo.Aresta (2, 4, 10);
        grafo.insereAresta (2,4,c2.peso());
        grafo.insereAresta (4,2,c2.peso());
        JGrafo.Aresta c3 =  new JGrafo.Aresta (2, 6, 5);
        grafo.insereAresta (2,6,c3.peso());
        grafo.insereAresta (6,2,c3.peso());        
        JGrafo.Aresta d1 =  new JGrafo.Aresta (3, 4, 5);
        grafo.insereAresta (3,4,d1.peso());
        grafo.insereAresta (4,3,d1.peso());      
        JGrafo.Aresta d2 =  new JGrafo.Aresta (3, 6, 10);
        grafo.insereAresta (3,6,d2.peso());
        grafo.insereAresta (6,3,d2.peso());       
        JGrafo.Aresta e1 =  new JGrafo.Aresta (4, 8, 10);
        grafo.insereAresta (4,8,e1.peso());
        grafo.insereAresta (8,4,e1.peso());       
        JGrafo.Aresta f1 =  new JGrafo.Aresta (5, 6, 15);
        grafo.insereAresta (5,6,f1.peso());
        grafo.insereAresta (6,5,f1.peso());
        JGrafo.Aresta h1 =  new JGrafo.Aresta (7, 8, 20);
        grafo.insereAresta (7,8,h1.peso());
        grafo.insereAresta (8,7,h1.peso());
        Grafo1 = new  JAGM(grafo);
        Grafo1.obterAgm(0);
        Grafo1.imprime();
        
        JGrafo grafo2 = new JGrafo (8, 17);
        JGrafo.Aresta a21 =  new JGrafo.Aresta (1, 0, 8);
        grafo2.insereAresta (1,0,a21.peso());
        grafo2.insereAresta (0,1,a21.peso());
        JGrafo.Aresta a22 =  new JGrafo.Aresta (1, 2, 3);
        grafo2.insereAresta (1,2,a22.peso());
        grafo2.insereAresta (2,1,a22.peso());
        JGrafo.Aresta a23 =  new JGrafo.Aresta (1, 3, 2);
        grafo2.insereAresta (1,3,a23.peso());
        grafo2.insereAresta (3,1,a23.peso());
        JGrafo.Aresta a24 =  new JGrafo.Aresta (1, 4, 7);
        grafo2.insereAresta (1,4,a24.peso());
        grafo2.insereAresta (4,1,a24.peso());
        JGrafo.Aresta a25 =  new JGrafo.Aresta (1, 5, 5);
        grafo2.insereAresta (1,5,a25.peso());
        grafo2.insereAresta (5,1,a25.peso());
        JGrafo.Aresta a26 =  new JGrafo.Aresta (1, 7, 6);
        grafo2.insereAresta (1,7,a26.peso());
        grafo2.insereAresta (7,1,a26.peso());     
        JGrafo.Aresta a71 =  new JGrafo.Aresta (6, 0, 9);
        grafo2.insereAresta (6,0,a71.peso());
        grafo2.insereAresta (0,6,a71.peso());  
        JGrafo.Aresta a73 =  new JGrafo.Aresta (6, 2, 6);
        grafo2.insereAresta (6,2,a73.peso());
        grafo2.insereAresta (2,6,a73.peso());  
        JGrafo.Aresta a74 =  new JGrafo.Aresta (6, 3, 2);
        grafo2.insereAresta (6,3,a74.peso());
        grafo2.insereAresta (3,6,a74.peso());  
        JGrafo.Aresta a75 =  new JGrafo.Aresta (6, 4, 4);
        grafo2.insereAresta (6,4,a75.peso());
        grafo2.insereAresta (4,6,a75.peso());  
        JGrafo.Aresta a76 =  new JGrafo.Aresta (6, 5, 6);
        grafo2.insereAresta (6,5,a76.peso());
        grafo2.insereAresta (5,6,a76.peso());  
        JGrafo.Aresta a78 =  new JGrafo.Aresta (6, 7, 1);
        grafo2.insereAresta (6,7,a78.peso());
        grafo2.insereAresta (7,6,a78.peso());          
        JGrafo.Aresta a13 =  new JGrafo.Aresta (0, 2, 2);
        grafo2.insereAresta (0,2,a13.peso());
        grafo2.insereAresta (2,0,a13.peso());
        JGrafo.Aresta a34 =  new JGrafo.Aresta (2, 3, 9);
        grafo2.insereAresta (2,3,a34.peso());
        grafo2.insereAresta (3,2,a34.peso());
        JGrafo.Aresta a45 =  new JGrafo.Aresta (3, 4, 6);
        grafo2.insereAresta (3,4,a45.peso());
        grafo2.insereAresta (4,3,a45.peso());
        JGrafo.Aresta a56 =  new JGrafo.Aresta (4, 5, 5);
        grafo2.insereAresta (4,5,a56.peso());
        grafo2.insereAresta (5,4,a56.peso());
        JGrafo.Aresta a68 =  new JGrafo.Aresta (5, 7, 4);
        grafo2.insereAresta (5,7,a68.peso());
        grafo2.insereAresta (7,5,a68.peso());
        System.out.println("\n\n");
        Grafo2 = new  JAGM(grafo2);
        Grafo2.obterAgm(0);
        Grafo2.imprime();       
    }
    
}
